### ISSUE TITLE
Clone or reference your image?

### ISSUE THREAD

**Issue by Sh4kE** [dockerfiles/django-uwsgi-nginx#12]
Hi,
This might be a really dumb question, but I can't figure out how to use your dockerfile in my app.

Should I clone your repository into my own django project and change it to my likings? (Like deleting the manage.py run command and such)

Or can I make a new Dockerfile and just extend yours with `FROM dockerfiles/django-uwsgi-nginx` and add steps for adding my own project into the app folder as well?

**Comment by dhrp** [comment]
The main purpose of this repository is showing *how* you can setup and run Django with Nginx in a container. 

So, the best way to use this repository is as an example. Clone the repository to a location of you liking, and start adding your files / change the configuration as needed. Once you're really into making your project you'll notice you've touched most files here.

**Comment by dhrp** [comment]
I updated the README btw
