### ISSUE TITLE
cannot build image

### ISSUE THREAD

**Issue by cip123** [dockerfiles/django-uwsgi-nginx#15]
cloned the repository but when i do a `docker build -t <name> .` 
I get :

`Step 3 : RUN apt-get update && apt-get install -y 	git 	python 	python-dev 	python-setuptools 	nginx 	supervisor 	sqlite3   && rm -rf /var/lib/apt/lists/*
 ---> Running in 5e9a1493a7ee
Container command '/bin/sh' not found or does not exist.`

**Comment by cip123** [comment]
Sorry, it was an archlinux fault, I reinstalled docker and restarted the daemon and everything works now

**Comment by dhrp** [comment]
ok, glad to hear.
