### ISSUE TITLE
"Internal Server Error" with my own Django project while running docker 

### ISSUE THREAD

**Issue by nuriyevn** [dockerfiles/django-uwsgi-nginx#26]
During running my Django project I get  "Internal Server Error"
instead of the requested page.
Simply that. Only three words as a page.

However, when I try to set up the dummy/empty Django project  - I am managed to set up everything without "Internal Server Error".

Question: how to troubleshoot this and what component is worth to dig into to tackle the bug?

**Comment by winz87** [comment]
modify "uwsgi.ini"

module=website.wsgi:application => module={your project name}.wsgi:application

**Comment by nuriyevn** [comment]
Yes!
Also, it can be caused by non-installed dependencies in python env.
