### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by SpencerCooley** [dockerfiles/django-uwsgi-nginx#3]
When I try to build I get this message. 
docker build -t webapp .

The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
                   Depends: g++ (>= 4:4.4.3) but it is not going to be installed
                   Depends: dpkg-dev (>= 1.13.5) but it is not going to be installed
 git : Depends: perl-modules but it is not going to be installed
       Depends: liberror-perl but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
2014/09/10 06:02:34 The command [/bin/sh -c apt-get install -y build-essential git] returned a non-zero code: 100

**Comment by ShadySQL** [comment]
you can also add:
echo "deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -sc) main universe" >> /etc/apt/sources.list

**Comment by bengolder** [comment]
@dhrp Are you still maintaining this repo?
It looks like there are two open pull requests that solve this issue, and they're almost a year old.
Should we be using someone else's fork as the official **dockerfiles** version?

**Comment by dhrp** [comment]
hey guys, @bengolder, sorry for not seeing these comments and PR's ever. I've had notifications sent to an address I no longer have :-/

**Comment by dhrp** [comment]
I updated the Dockerfile to 2016, solved these problems.
